// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockMonitoringCommunity.Data;

#nullable disable

namespace StockMonitoringCommunity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106082542_9_packaging_table")]
    partial class _9_packaging_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockMonitoringCommunity.Data.AccumulateStockLog", b =>
                {
                    b.Property<int>("AccumulateStockLog_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccumulateStockLog_ID"));

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Partnumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AccumulateStockLog_ID");

                    b.ToTable("AccumulateStockLogs");
                });

            modelBuilder.Entity("StockMonitoringCommunity.Data.Comport", b =>
                {
                    b.Property<int>("Channel_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Baudrate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataBits")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("Handshake")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Pattern1")
                        .HasColumnType("integer");

                    b.Property<int>("Pattern2")
                        .HasColumnType("integer");

                    b.Property<int>("Pattern3")
                        .HasColumnType("integer");

                    b.Property<int>("Pattern4")
                        .HasColumnType("integer");

                    b.Property<int>("Pattern5")
                        .HasColumnType("integer");

                    b.Property<int>("Pattern6")
                        .HasColumnType("integer");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Stopbit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Channel_ID");

                    b.ToTable("Comports");
                });

            modelBuilder.Entity("StockMonitoringCommunity.Data.InputPattern", b =>
                {
                    b.Property<int>("Pattern_ID")
                        .HasColumnType("integer");

                    b.Property<string>("ExampleText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("NumberOfCharactor")
                        .HasColumnType("integer");

                    b.Property<bool>("PatternCheck")
                        .HasColumnType("boolean");

                    b.Property<string>("Result")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("StartCharactor")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOfCharactor")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueStart")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueText")
                        .HasColumnType("text");

                    b.HasKey("Pattern_ID");

                    b.ToTable("InputPatterns");
                });

            modelBuilder.Entity("StockMonitoringCommunity.Data.MasterStock", b =>
                {
                    b.Property<int>("Stock_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Stock_ID"));

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("Invisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("LowerLimit")
                        .HasColumnType("integer");

                    b.Property<int>("LowerWarningLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Partnumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StoreID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UpperLimit")
                        .HasColumnType("integer");

                    b.Property<int>("UpperWarningLimit")
                        .HasColumnType("integer");

                    b.HasKey("Stock_ID");

                    b.ToTable("MasterStocks");
                });

            modelBuilder.Entity("StockMonitoringCommunity.Data.Packaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Partnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerScantimes")
                        .HasColumnType("integer");

                    b.Property<string>("StoreID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Packagings");
                });

            modelBuilder.Entity("StockMonitoringCommunity.Data.ScanInOutTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Partnumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("ScanInOutTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
